version: 2.1
# add your orb below, to be used in integration tests (note: a @dev:alpha
# release must exist.);
orbs:
  browser-tools: circleci/browser-tools@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@9.1
  jq: circleci/jq@2.0

executors:
  docker-cimg:
    docker:
      - image: cimg/base:stable
  macos-11-4:
    macos:
      xcode: 11.4.0
  machine-16:
    machine:
      image: ubuntu-1604:201903-01
# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

jobs:
  integration-tests:
    parameters:
      executor:
        type: executor
      firefox-version:
        type: string
        default: latest
      geckodriver-version:
        type: string
        default: latest
      replace-existing-chrome:
        type: boolean
        default: true
      chrome-version:
        type: string
        default: latest
    executor: <<parameters.executor>>
    steps:
      - jq/install
      - browser-tools/install-browser-tools:
          firefox-version: <<parameters.firefox-version>>
          replace-existing-chrome: <<parameters.replace-existing-chrome>>
          chrome-version: <<parameters.chrome-version>>

workflows:
  # This `lint-pack_validate_publish-dev` workflow will run on any commit.
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/shellcheck:
          exclude: "SC1009,SC1073,SC1041,SC1042"
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: circleci/browser-tools
          context: orb-publisher
          requires:
            - orb-tools/lint
            - orb-tools/shellcheck
            - orb-tools/pack
      # trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publisher
          requires:
            - orb-tools/publish-dev

  # This `integration-tests_prod-release` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  integration-tests_prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-tests:
          name: test-docker
          executor: docker-cimg
      - integration-tests:
          name: test-specific-version
          executor: docker-cimg
          chrome-version: "85.0.4183.102"
          firefox-version: "80.0.1"
      - integration-tests:
          name: test-macos
          executor: macos-11-4
      - integration-tests:
          name: test-machine-16
          executor: machine-16

      # publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: circleci/browser-tools
          context: orb-publisher
          add-pr-comment: true
          bot-token-variable: GHI_TOKEN
          bot-user: orb-publisher
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          ssh-fingerprints: d5:f2:f8:4b:91:76:27:e6:09:2b:ad:06:ac:8f:fa:3e
          requires:
            - test-docker
            - test-macos
            - test-machine-16
          filters:
            branches:
              only: master
