version: 2.1
orbs:
  browser-tools: circleci/browser-tools@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1
  jq: circleci/jq@2.2
filters: &filters
  tags:
    only: /.*/
jobs:
  int-test-all:
    parameters:
      executor:
        type: executor
      firefox-version:
        type: string
        default: latest
      geckodriver-version:
        type: string
        default: latest
      replace-existing-chrome:
        type: boolean
        default: true
      chrome-version:
        type: string
        default: latest
    executor: <<parameters.executor>>
    steps:
      - jq/install
      - browser-tools/install-browser-tools:
          firefox-version: <<parameters.firefox-version>>
          replace-existing-chrome: <<parameters.replace-existing-chrome>>
          chrome-version: <<parameters.chrome-version>>
  int-test-chrome:
    parameters:
      executor:
        type: executor
      firefox-version:
        type: string
        default: latest
      geckodriver-version:
        type: string
        default: latest
      replace-existing-chrome:
        type: boolean
        default: true
      chrome-version:
        type: string
        default: latest
    executor: <<parameters.executor>>
    steps:
      - jq/install
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
  int-test-firefox:
    parameters:
      executor:
        type: executor
      firefox-version:
        type: string
        default: latest
      geckodriver-version:
        type: string
        default: latest
      replace-existing-chrome:
        type: boolean
        default: true
      chrome-version:
        type: string
        default: latest
    executor: <<parameters.executor>>
    steps:
      - jq/install
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
workflows:
  test-deploy:
    jobs:
      - int-test-all:
          name: test-cimg-base-all
          executor: cimg-base
          filters: *filters
      - int-test-all:
          name: test-cimg-node-all
          executor: cimg-node
          filters: *filters
      - int-test-all:
          name: test-specific-version-all
          executor: cimg-base
          chrome-version: "92.0.4515.131"
          firefox-version: "90.0.1"
          filters: *filters
      - int-test-all:
          name: test-macos-all
          executor: macos
          filters: *filters
      - int-test-all:
          name: test-linux-all
          executor: linux
          filters: *filters
      - int-test-chrome:
          name: test-cimg-base-chrome
          executor: cimg-base
          filters: *filters
      - int-test-chrome:
          name: test-cimg-node-chrome
          executor: cimg-node
          filters: *filters
      - int-test-chrome:
          name: test-specific-version-chrome
          executor: cimg-base
          chrome-version: "92.0.4515.131"
          firefox-version: "90.0.1"
          filters: *filters
      - int-test-chrome:
          name: test-macos-chrome
          executor: macos
      - int-test-chrome:
          name: test-linux-chrome
          executor: linux
          filters: *filters
      - int-test-firefox:
          name: test-cimg-base-firefox
          executor: cimg-base
          filters: *filters
      - int-test-firefox:
          name: test-cimg-node-firefox
          executor: cimg-node
          filters: *filters
      - int-test-firefox:
          name: test-specific-version-firefox
          executor: cimg-base
          chrome-version: "92.0.4515.131"
          firefox-version: "90.0.1"
          filters: *filters
      - int-test-firefox:
          name: test-macos-firefox
          executor: macos
          filters: *filters
      - int-test-firefox:
          name: test-linux-firefox
          executor: linux
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: circleci/browser-tools
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - test-cimg-base-all
            - test-cimg-node-all
            - test-macos-all
            - test-linux-all
            - test-cimg-base-chrome
            - test-cimg-node-chrome
            - test-macos-chrome
            - test-linux-chrome
            - test-cimg-base-firefox
            - test-cimg-node-firefox
            - test-macos-firefox
            - test-linux-firefox
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
executors:
  cimg-base:
    docker:
      - image: cimg/base:stable
  cimg-node:
    docker:
      - image: cimg/node:lts-browsers
  cimg-openjdk:
    docker:
      - image: cimg/openjdk:11.0-browsers
  macos:
    macos:
      xcode: 12.5.1
  linux:
    machine:
      image: ubuntu-2004:202107-02
